type attribute_name = Symbol | String

class KVStruct < Struct[Object]
  def self.new: (*attribute_name) ?{ () -> void } -> KVStruct
              | (Array[attribute_name]) ?{ () -> void } -> KVStruct
              | (*attribute_name, Array[attribute_name]) ?{ () -> void } -> KVStruct

  def initialize: (Hash[attribute_name, Object]) -> KVStruct
end

class RStruct < Struct[Object]
  def self.new: (*attribute_name) ?{ () -> void } -> RStruct
              | (Array[attribute_name]) ?{ () -> void } -> RStruct
              | (*attribute_name, Array[attribute_name]) ?{ () -> void } -> RStruct

  def initialize: (*Object args) -> RStruct
end
