class Struct[Elem]
  type attribute_name = Symbol | String
end

class KVStruct < Struct[Elem]
  def self.new: (*attribute_name | Array[attribute_name]) { () -> void } -> KVStruct

  def initialize(Hash[attribute_name, Object]) -> KVStruct
end

class RStruct < Struct[Elem]
  def self.new: def self.new: (*attribute_name | Array[attribute_name]) { () -> void } -> RStruct

  def initialize: (*Object args) -> RStruct
end
